I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/alphaphi.rpy", line 25, in script
    cgod "Do you want to pull?"
Exception: Sayer 'cgod' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/alphaphi.rpy", line 25, in script
    cgod "Do you want to pull?"
  File "C:\Users\Ezekiel\Documents\SoS\renpy-6.99.10-sdk\renpy\ast.py", line 584, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Ezekiel\Documents\SoS\renpy-6.99.10-sdk\renpy\ast.py", line 501, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'cgod' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.10.1227
Seasons of Stella 0.0
